ci: disable cgo

diff --git a/.github/workflows/mini.yml b/.github/workflows/mini.yml
--- a/.github/workflows/mini.yml
+++ b/.github/workflows/mini.yml
@@ -44,6 +44,11 @@ jobs:
         run: |
           echo "CGO_ENABLED=1" >> $GITHUB_ENV
 
+      - name: Disable CGO
+        if: ${{ matrix.cgo != '-cgo' }}
+        run: |
+          echo "CGO_ENABLED=0" >> $GITHUB_ENV
+
       - name: Install Go
         uses: actions/setup-go@v5
         with:
@@ -56,8 +61,8 @@ jobs:
       - name: Build pure exe
         shell: bash
         run: |
-          go build -a -buildmode=exe -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}${{ matrix.cgo }} . || true
-          go build -a -buildmode=exe -ldflags="-s -w" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip${{ matrix.cgo }} . || true
+          go build -a -buildmode=exe -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
+          go build -a -buildmode=exe -ldflags="-s -w" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
         env:
           GOOS: ${{ matrix.platform }}
           GOARCH: ${{ matrix.arch }}
@@ -65,14 +70,14 @@ jobs:
       - name: Build pure pie
         shell: bash
         run: |
-          go build -a -buildmode=pie -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-pie . || true
-          go build -a -buildmode=pie -ldflags="-s -w" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-pie${{ matrix.cgo }} . || true
+          go build -a -buildmode=pie -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-pie . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
+          go build -a -buildmode=pie -ldflags="-s -w" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-pie${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
 
       - name: Build external exe
         shell: bash
         run: |
-          go build -a -buildmode=exe -ldflags="-linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-ext${{ matrix.cgo }} . || true
-          go build -a -buildmode=exe -ldflags="-s -w -linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-ext${{ matrix.cgo }} . || true
+          go build -a -buildmode=exe -ldflags="-linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-ext${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
+          go build -a -buildmode=exe -ldflags="-s -w -linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-ext${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
         env:
           GOOS: ${{ matrix.platform }}
           GOARCH: ${{ matrix.arch }}
@@ -80,8 +85,8 @@ jobs:
       - name: Build external pie
         shell: bash
         run: |
-          go build -a -buildmode=pie -ldflags="-linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-ext-pie${{ matrix.cgo }} . || true
-          go build -a -buildmode=pie -ldflags="-s -w -linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-ext-pie${{ matrix.cgo }} . || true
+          go build -a -buildmode=pie -ldflags="-linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-ext-pie${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
+          go build -a -buildmode=pie -ldflags="-s -w -linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-ext-pie${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
         env:
           GOOS: ${{ matrix.platform }}
           GOARCH: ${{ matrix.arch }}
@@ -120,6 +125,10 @@ jobs:
         run: |
           echo "CGO_ENABLED=1" >> $GITHUB_ENV
 
+      - name: Disable CGO
+        if: ${{ matrix.cgo != '-cgo' }}
+        run: |
+          echo "CGO_ENABLED=0" >> $GITHUB_ENV
 
       - name: Install Go
         uses: actions/setup-go@v5
@@ -133,8 +142,8 @@ jobs:
       - name: Build pure exe
         shell: bash
         run: |
-          go build -a -buildmode=exe -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}${{ matrix.cgo }} . || true
-          go build -a -buildmode=exe -ldflags="-s -w" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip${{ matrix.cgo }} . || true
+          go build -a -buildmode=exe -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
+          go build -a -buildmode=exe -ldflags="-s -w" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
         env:
           GOOS: ${{ matrix.platform }}
           GOARCH: ${{ matrix.arch }}
@@ -142,14 +151,14 @@ jobs:
       - name: Build pure pie
         shell: bash
         run: |
-          go build -a -buildmode=pie -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-pie${{ matrix.cgo }} . || true
-          go build -a -buildmode=pie -ldflags="-s -w" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-pie${{ matrix.cgo }} . || true
+          go build -a -buildmode=pie -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-pie${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
+          go build -a -buildmode=pie -ldflags="-s -w" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-pie${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
 
       - name: Build external exe
         shell: bash
         run: |
-          go build -a -buildmode=exe -ldflags="-linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-ext${{ matrix.cgo }} . || true
-          go build -a -buildmode=exe -ldflags="-s -w -linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-ext${{ matrix.cgo }} . || true
+          go build -a -buildmode=exe -ldflags="-linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-ext${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
+          go build -a -buildmode=exe -ldflags="-s -w -linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-ext${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
         env:
           GOOS: ${{ matrix.platform }}
           GOARCH: ${{ matrix.arch }}
@@ -157,8 +166,8 @@ jobs:
       - name: Build external pie
         shell: bash
         run: |
-          go build -a -buildmode=pie -ldflags="-linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-ext-pie${{ matrix.cgo }} . || true
-          go build -a -buildmode=pie -ldflags="-s -w -linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-ext-pie${{ matrix.cgo }} . || true
+          go build -a -buildmode=pie -ldflags="-linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-ext-pie${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
+          go build -a -buildmode=pie -ldflags="-s -w -linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-ext-pie${{ matrix.cgo }} . || echo "Failed to build" >> $GITHUB_STEP_SUMMARY
         env:
           GOOS: ${{ matrix.platform }}
           GOARCH: ${{ matrix.arch }}
@@ -185,7 +194,7 @@ jobs:
       - name: Create Release
         uses: softprops/action-gh-release@v1
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
         with:
           tag_name: latest
           name: "Release"
